version: 2
jobs:
  build:
    working_directory: ~/solidus
    environment:
      SOLIDUS_RAISE_DEPRECATIONS: true
    docker:
      - image: circleci/ruby:2.3.4-node-browsers
        environment:
          RAILS_ENV: test
          RACK_ENV: test
          PGHOST: 127.0.0.1
      - image: circleci/postgres:9.6.2-alpine
        command: -c fsync=off -c full_page_writes=off
    parallelism: 3
    steps:
      - checkout

      - restore_cache:
          name: Restore bundle cache
          keys:
            - solidus-bundle-v1-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install dependencies
          command: |
            bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - run:
          name: Install postgresql client
          command: |
            sudo apt-get update
            sudo apt-get install postgresql-client

      - save_cache:
          name: Store bundle cache
          key: solidus-bundle-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Setup database
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load --trace

      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --profile 10 \
                              --format progress \
                              --format RspecJunitFormatter \
                              -o tmp/test-results/rspec-#{$CIRCLE_NODE_INDEX}.xml \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      - store_artifacts:
          path: tmp/capybara

      - store_test_results:
          path: tmp/test-results

  push_image:
    working_directory: ~/solidus
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout #TODO: copy files here instead of new checkout

      - setup_remote_docker

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Build runtime Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t eu.gcr.io/$GOOGLE_PROJECT_ID/solidus-runtime:$TAG \
                         -f Dockerfile.runtime .

      - run:
          name: Check if it worked
          command: docker images

      - run:
          name: Decode Google Cloud Credentials
          command: |
            echo ${GOOGLE_AUTH} | base64 -i --decode > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - push_image:
          requires:
            - build
#
# # create a alpine-based build container to ensure that the ruby gems with C-bindings are compiled with musil instead of libc.
#
# Build a docker image that contains a working solidus shop but no build tools for it. Only things we need at runtime.
# It should be based on alpine and generate no files on its own but rather copy the generated files from the build-container.
#
# Push the image to Google Container Registry using at least the git hash as a label and maybe additional ones.
#
# Tell the Kubernetes cluster to create a kubernetes-deployment that uses the previously built-and-pushed container image.
# Also define a service and an ingress controller that points to the pods created to the deployment.
#
